---
dependency:
  name: galaxy
provisioner:
  name: ansible
driver:
  name: podman
platforms:
  - name: centos_os
    image: docker.io/geerlingguy/docker-centos8-ansible 
verifier:
  name: ansible
lint: |
  set -e
